FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app
COPY *.csproj .
RUN dotnet restore

COPY . .

CMD ["dotnet", "watch", "run", "--project", "api.csproj", "--urls", "http://*:8080", "--non-interactive"]